name: Terraform

on:
  workflow_run:
    workflows: ["Create S3 Bucket"]
    types:
      - completed
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init -migrate-state

    - name: Terraform Plan
      env:
        TF_VAR_github_token: ${{ secrets.SECRET_TOKEN }}
        TF_VAR_github_webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
      run: terraform plan

    - name: Terraform Apply
      if: github.event_name == 'workflow_dispatch'  # Only run apply on manual trigger
      env:
        TF_VAR_github_token: ${{ secrets.SECRET_TOKEN }}
        TF_VAR_github_webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
      run: terraform apply -auto-approve